---
- name: Modify sshd settings
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    state: present
    backrefs: true
    regexp: '{{ item.regexp }}'
    line: '{{ item.line }}'
  with_items:
    - regexp: '^#?\s*PermitRootLogin'
      line: 'PermitRootLogin without-password'
    - regexp: '^#?\s*PasswordAuthentication'
      line: 'PasswordAuthentication no'
    - regexp: '^#?\s*PubkeyAuthentication'
      line: 'PubkeyAuthentication yes'
  notify:
    - Restart sshd
