---
- name: Add OS package repo
  ansible.builtin.command:
    cmd: dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  args:
    creates: /etc/yum.repos.d/docker-ce.repo

- name: Install OS packages
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
  with_items:
    - docker-ce-23.0.1
    - docker-ce-cli-23.0.1
    - containerd.io-1.6.18
    - docker-buildx-plugin-0.10.2
    - docker-compose-plugin-2.16.0

- name: Start OS services
  service:
  # ansible.builtin.service:
    name: docker
    state: started
    enabled: true

# - name: Add users to docker group
#   ansible.builtin.user:
#     name: "{{ item }}"
#     groups: docker
#     append: true
#   with_items:
#     - "{{ user }}"
